### ISSUE TITLE
Knockoff is a black-box attack, why TEE-slice can work?

### ISSUE THREAD

**Issue by zyma-Jasper** [ziqi-zhang/TEESlice-artifact#1]
The original Knockoff paper notes this is a black-box attack. How can TEE-slice work for a black-box attack?

**Comment by ziqi-zhang** [comment]
Hi, thanks for the comments. 

Yes, the Knockoff paper is a black-box attack, and TEESlice does not aim to defend against black-box attacks by itself.

The scenario we considered is that the model owner deploys a private DNN model to a customer's device, thus the private DNN model becomes a white box to the device owner. The owner can perform the white-box attack. The goal of TEESlice (and prior TSDP papers) is to downgrade the white-box attack to a black-box attack. In other words, the ideal protection with the highest security is to put the whole DNN into the TEE of the users' device, which the device owner can only perform a black-box attack.

As for defending against black-box attacks, TEESlice (and other TSDP papers) can be integrated with other black-box protections. You can refer MLCapsule for the integration with TSDP and black-box defense.

**Comment by zyma-Jasper** [comment]
Now I fully understand it, thanks for your clarification!

**Comment by ziqi-zhang** [comment]
You're welcome!
