### ISSUE TITLE
Where are the scripts for performing MIA?

### ISSUE THREAD

**Issue by suntong30** [ziqi-zhang/TEESlice-artifact#2]
The README.md describes that  `membership-inference/scripts` contains the script to run the code, but I cannot find the folder. How do we perform membership inference attacks?

**Comment by ziqi-zhang** [comment]
Thanks for the reminder! I uploaded the scripts for MIA in `membership-inference/scripts` just now.

**Comment by suntong30** [comment]
Thanks for your code. I'm a little confused right now, hope you can help me. (1) For model stealing, TEESlice uses knockoff nets, which is a query-based attack. For the previous method of shielding partial parameters, does the attacker only use the leaked parameters as the initialization value of the surrogate model? (2) For MIA, how do they carry out attacks based on the leaked intermediate results? I am confused about the TEESlice code. Thanks a lot if you could tell me.

**Comment by ziqi-zhang** [comment]
Thanks for your great questions.

For the first question, the attackers use two parts to initialize the surrogate model. For the part on GPU, the attacker can directly use the leaked parameters. For the part shielded by TEE, the attacker uses the values from the public model as initialization. After the initialization, the attacker can follow standard query-based attack (e.g. knockoff) to train the complete model. So the additional information the attacker acquires compared knockoff is the leaked parameters on the GPUs.

For the second question, the attacker can use the trained surrogate model (the output of model stealing) to perform MIA. For example, using the model confidence or loss to distinguish member/nonmember data.

**Comment by suntong30** [comment]
Thanks for your clarification. I currently fully understand the first question. However, I am still confused about the second question.  The DarkneTZ and other approaches (e.g., ShadowNet), seem to protect the loss and confidence in the TEE. Why are they still vulnerable to MIA? This is because attackers can first train a surrogate model with good performance, so can know loss and confidence from the surrogate model, right? But I find that seems the ML-Doctor/KnockoffNets didn't utilize the leaked information about intermediate results for building surrogate models, am I right? Thanks a ton if you can help me.

**Comment by ziqi-zhang** [comment]
HI, sorry for the late reply.

You are right. We focus on the amount of membership leaked from the unprotected model weights, which is different from prior work DarkneTZ/ML-Doctor/KnockoffNets. This is a unique leakage for TEE-Shielded DNN partition scenarios. The major point of our MIA is that the attacker uses the unprotected layers to construct the surrogate model, and the membership privacy inside the unprotected layers can leaked through the surrogate model.

**Comment by suntong30** [comment]
Thank you for your reply, I currently fully understand :)
