### ISSUE TITLE
Inquiry About Source Code for : On the (In-)Security of TEE-Shielded DNN Partition for On-Device ML

### ISSUE THREAD

**Issue by ywtdas** [ziqi-zhang/TEESlice-artifact#4]
I am honored to have read your article on On the (In -) Security of TEE Shielded DNN Partition for On Device ML at the IEEE Symposium on Security and Privacy. When I tried to reproduce the content of Figure 2 in the paper, I found that the student model and teacher model of Alexnet and VGG were missing from the code. Could you please provide the source code or model structure of these two contents, as well as specific SLICE details?

**Comment by Siyan410** [comment]
I encountered a similar problem. How did you finally solve it?
